//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTelecom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Categories
    {
        public T_Categories()
        {
            this.T_Products = new HashSet<T_Products>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<T_Products> T_Products { get; set; }
    }
}
