//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTelecom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Products
    {
        public T_Products()
        {
            this.T_OrderDetails = new HashSet<T_OrderDetails>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public double ProductPrice { get; set; }
        public int CategoryId { get; set; }
    
        public virtual T_Categories T_Categories { get; set; }
        public virtual ICollection<T_OrderDetails> T_OrderDetails { get; set; }
    }
}
